---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/awx-ee:latest
  EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:latest
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
additional_build_steps:
  prepend:  |
    RUN dnf upgrade -y
    RUN pip3 install --upgrade pip setuptools

